import React from 'react';
import { AbsoluteFill, Audio, Sequence, Series, staticFile } from 'remotion';
import { SCENES, COLORS, FONT_FAMILY } from './constants';
import { HookScene } from './scenes/HookScene';
import { ProductIntroScene } from './scenes/ProductIntroScene';
import { ScanScene } from './scenes/ScanScene';
import { TenpaiScene } from './scenes/TenpaiScene';
import { Top6Scene } from './scenes/Top6Scene';
import { ValueScene } from './scenes/ValueScene';
import { VisibleTilesScene } from './scenes/VisibleTilesScene';
import { StrategyScene } from './scenes/StrategyScene';
import { ScoringScene } from './scenes/ScoringScene';
import { QuizScene } from './scenes/QuizScene';
import { EndScene } from './scenes/EndScene';

const SCENE_MAP: Record<string, React.FC> = {
  hook: HookScene,
  productIntro: ProductIntroScene,
  scan: ScanScene,
  tenpai: TenpaiScene,
  top6: Top6Scene,
  value: ValueScene,
  visibleTiles: VisibleTilesScene,
  strategy: StrategyScene,
  scoring: ScoringScene,
  quiz: QuizScene,
  end: EndScene,
};

/**
 * Voice / BGM wiring.
 *
 *   public/audio/voice-{01..11}.mp3   ← edge-tts, generated by scripts/build-voice.py
 *   public/audio/bgm.mp3              ← OPTIONAL background music; loops the whole video
 *
 * Missing files don't break the build — Remotion's <Audio> only complains if it
 * can't fetch the file at render time, so we feed paths conditionally.
 */
const HAS_BGM = false; // flip to true after placing public/audio/bgm.mp3

/**
 * Per-scene voice delay, in frames, on top of SCENES[i].from.
 * Use to push a clip back when the previous line hasn't finished yet.
 * Index matches SCENES[].
 */
const VOICE_OFFSET: number[] = [
  0,  // 01 hook
  0,  // 02 productIntro
  0,  // 03 scan
  0,  // 04 tenpai
  0,  // 05 top6
  0,  // 06 value
  0,  // 07 visibleTiles
  0,  // 08 strategy
  0,  // 09 scoring
  0,  // 10 quiz
  60, // 11 end — wait 2s. voice-10 even at 1.18× ends near 57.5s, so start 11 at 58s.
];

/**
 * Per-scene playback rate. 1.0 = original. 1.15 = 15% faster (and slightly higher pitch).
 * Use when a clip is too long to fit its scene without overlapping the next line.
 */
const VOICE_RATE: number[] = [
  1.15, // 01 hook — tighten so it doesn't bleed into product intro
  1.0,  // 02
  1.0,  // 03
  1.0,  // 04
  1.0,  // 05
  1.0,  // 06
  1.0,  // 07
  1.0,  // 08
  1.0,  // 09
  1.18, // 10 quiz — original 7.7s won't fit in the 5s scene; speed up + push #11 back
  1.0,  // 11
];

export const PromoVideo: React.FC = () => {
  return (
    <AbsoluteFill
      style={{
        background: COLORS.bgCream,
        fontFamily: FONT_FAMILY,
        color: COLORS.sage800,
      }}
    >
      {/* Optional BGM under everything; ducked low so it never fights the voice. */}
      {HAS_BGM && (
        <Audio src={staticFile('audio/bgm.mp3')} volume={0.18} loop />
      )}

      {/* 11 voice clips, each anchored to its scene's start frame + per-clip offset. */}
      {SCENES.map((s, i) => (
        <Sequence key={`v-${s.id}`} from={s.from + (VOICE_OFFSET[i] ?? 0)}>
          <Audio
            src={staticFile(`audio/voice-${String(i + 1).padStart(2, '0')}.mp3`)}
            volume={1}
            playbackRate={VOICE_RATE[i] ?? 1}
          />
        </Sequence>
      ))}

      <Series>
        {SCENES.map((s) => {
          const Comp = SCENE_MAP[s.id];
          return (
            <Series.Sequence key={s.id} durationInFrames={s.duration}>
              <Comp />
            </Series.Sequence>
          );
        })}
      </Series>
    </AbsoluteFill>
  );
};
