import React from 'react';
import { AbsoluteFill, Audio, Sequence, Series, staticFile } from 'remotion';
import { SCENES, COLORS, FONT_FAMILY } from './constants';
import { HookScene } from './scenes/HookScene';
import { ProductIntroScene } from './scenes/ProductIntroScene';
import { InputScene } from './scenes/InputScene';
import { TenpaiScene } from './scenes/TenpaiScene';
import { Top6Scene } from './scenes/Top6Scene';
import { AICoachScene } from './scenes/AICoachScene';
import { VisibleTilesScene } from './scenes/VisibleTilesScene';
import { StrategyScene } from './scenes/StrategyScene';
import { ScoringScene } from './scenes/ScoringScene';
import { QuizScene } from './scenes/QuizScene';
import { EndScene } from './scenes/EndScene';

const SCENE_MAP: Record<string, React.FC> = {
  hook: HookScene,
  productIntro: ProductIntroScene,
  input: InputScene,
  tenpai: TenpaiScene,
  top6: Top6Scene,
  aiCoach: AICoachScene,
  visibleTiles: VisibleTilesScene,
  strategy: StrategyScene,
  scoring: ScoringScene,
  quiz: QuizScene,
  end: EndScene,
};

/**
 * Voice / BGM wiring.
 *
 *   public/audio/voice-{01..11}.mp3   ← edge-tts, generated by scripts/build-voice.py
 *   public/audio/bgm.mp3              ← OPTIONAL background music; loops the whole video
 *
 * Missing files don't break the build — Remotion's <Audio> only complains if it
 * can't fetch the file at render time, so we feed paths conditionally.
 */
const HAS_BGM = false; // flip to true after placing public/audio/bgm.mp3

/**
 * Per-scene voice delay, in frames, on top of SCENES[i].from.
 * Index matches SCENES[]. With v2 lines all comfortably shorter than their
 * scenes, every entry can be 0.
 */
const VOICE_OFFSET: number[] = [
  0,  // 01 hook
  0,  // 02 productIntro
  0,  // 03 input
  0,  // 04 tenpai
  0,  // 05 top6
  0,  // 06 aiCoach ★
  0,  // 07 visibleTiles
  0,  // 08 strategy
  0,  // 09 scoring
  0,  // 10 quiz
  0,  // 11 end
];

/**
 * Per-scene playback rate, calibrated against actual mp3 lengths
 * (run `ffprobe -show_entries format=duration` after build-voice.py).
 * Goal: every clip ends ≥0.1s before its scene's end so lines never overlap.
 */
const VOICE_RATE: number[] = [
  1.10, // 01 hook            mp3 3.00s / scene 3s → 2.73s ✓
  1.05, // 02 productIntro    mp3 3.91s / scene 4s → 3.72s ✓
  1.05, // 03 input           mp3 2.95s / scene 3s → 2.81s ✓
  1.0,  // 04 tenpai          mp3 4.06s / scene 5s ✓
  1.0,  // 05 top6            mp3 5.66s / scene 7s ✓
  1.0,  // 06 aiCoach         mp3 8.74s / scene 9s ✓
  1.0,  // 07 visibleTiles    mp3 4.30s / scene 5s ✓
  1.0,  // 08 strategy        mp3 4.73s / scene 6s ✓
  1.0,  // 09 scoring         mp3 3.53s / scene 5s ✓
  1.0,  // 10 quiz            mp3 4.82s / scene 6s ✓
  1.0,  // 11 end             mp3 4.06s / scene 7s ✓
];

export const PromoVideo: React.FC = () => {
  return (
    <AbsoluteFill
      style={{
        background: COLORS.bgCream,
        fontFamily: FONT_FAMILY,
        color: COLORS.sage800,
      }}
    >
      {/* Optional BGM under everything; ducked low so it never fights the voice. */}
      {HAS_BGM && (
        <Audio src={staticFile('audio/bgm.mp3')} volume={0.18} loop />
      )}

      {/* 11 voice clips, each anchored to its scene's start frame + per-clip offset. */}
      {SCENES.map((s, i) => (
        <Sequence key={`v-${s.id}`} from={s.from + (VOICE_OFFSET[i] ?? 0)}>
          <Audio
            src={staticFile(`audio/voice-${String(i + 1).padStart(2, '0')}.mp3`)}
            volume={1}
            playbackRate={VOICE_RATE[i] ?? 1}
          />
        </Sequence>
      ))}

      <Series>
        {SCENES.map((s) => {
          const Comp = SCENE_MAP[s.id];
          return (
            <Series.Sequence key={s.id} durationInFrames={s.duration}>
              <Comp />
            </Series.Sequence>
          );
        })}
      </Series>
    </AbsoluteFill>
  );
};
